services:
    carteira-app:
        container_name: carteira-app
        build:
            dockerfile: ./docker/Dockerfile.server
        restart: unless-stopped
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000        
        volumes:
            - .:/app
            - ./staticfiles:/app/staticfiles
        env_file:
            - .env
        networks:
            - carteira-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
            interval: 10s
            timeout: 5s
            retries: 3

    carteira-nginx:
        image: nginx:latest
        container_name: carteira-nginx
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./staticfiles:/var/www/app/staticfiles
        ports:
            - 8000:80
        networks:
            - carteira-network
        depends_on:
            - carteira-app

    carteira-rabbitmq:
        container_name: carteira-rabbitmq
        image: rabbitmq:management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - carteira-network

    carteira-celery:
        container_name: carteira-celery
        build:
            dockerfile: ./docker/Dockerfile.celery
        restart: unless-stopped
        command: celery -A core worker -l INFO 
        volumes:
            - .:/app
        env_file:
            - .env
        networks:
            - carteira-network
        depends_on:
            - carteira-rabbitmq
            - carteira-app


    carteira-celery-beat:
        container_name: carteira-celery-beat
        build:
            dockerfile: ./docker/Dockerfile.celery
        restart: unless-stopped
        command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        volumes:
            - .:/app
        env_file:
            - .env
        networks:
            - carteira-network
        depends_on:
            - carteira-rabbitmq
            - carteira-app

networks:
    carteira-network:
        driver: bridge