FROM python:3.12-slim

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update 
RUN apt-get install -y curl  gnupg unixodbc-dev build-essential libpq-dev
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get clean -y

COPY .. /app/

RUN pip install --no-cache-dir -r ./docker/light_requirements.txt
