FROM python:3.12-slim

WORKDIR /app

RUN apt-get update 
RUN apt-get install -y curl  gnupg unixodbc-dev build-essential libpq-dev && rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get clean -y

COPY .. /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py loadassets

CMD ["gunicorn", "core.wsgi:application", "--bind 0.0.0.0:8000"]
