# Generated by Django 5.1.4 on 2024-12-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dividends',
            new_name='Dividend',
        ),
    ]
