# Generated by Django 5.1.4 on 2024-12-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_stocks', '0002_rename_dividends_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='apps_stocks.stock'),
        ),
    ]
