# Generated by Django 5.1.4 on 2025-01-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_stocks', '0004_rename_type_stocktype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_stocks.stocktype')),
            ],
        ),
    ]
