# Generated by Django 5.1.4 on 2025-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_stocks', '0005_stocksubtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksubtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
