# Generated by Django 5.1.4 on 2025-01-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_stocks', '0006_alter_stocksubtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_stocks.stocksubtype'),
            preserve_default=False,
        ),
    ]
