# Generated by Django 5.1.5 on 2025-01-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('code', 'asset_type')},
        ),
    ]
