# Generated by Django 5.1.5 on 2025-01-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0002_alter_asset_code_alter_asset_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprice',
            name='date',
            field=models.DateField(),
        ),
    ]
