# Generated by Django 5.1.5 on 2025-01-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0003_alter_assetprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='date',
            field=models.DateField(),
        ),
    ]
