# Generated by Django 5.1.5 on 2025-01-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0004_alter_dividend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=60),
        ),
    ]
