# Generated by Django 5.1.5 on 2025-01-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0006_alter_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
