# Generated by Django 5.1.5 on 2025-01-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0007_alter_asset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetprice',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
