# Generated by Django 5.1.5 on 2025-01-22 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0007_alter_asset_code'),
        ('apps_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodydividend',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custodydividend',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='custodydividend',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='custodydividend',
            unique_together={('custody', 'dividend')},
        ),
    ]
