# Generated by Django 5.1.5 on 2025-01-23 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_assets', '0007_alter_asset_code'),
        ('apps_operations', '0002_custodydividend_active_custodydividend_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('last_price', models.FloatField(default=0)),
                ('mean_price', models.FloatField(default=0)),
                ('dividend_amount_received', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
