# Generated by Django 5.1.5 on 2025-01-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_operations', '0003_custodysnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='custody',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='volume',
            field=models.FloatField(),
        ),
    ]
