# Generated by Django 5.1.4 on 2024-12-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_operations', '0004_alter_buy_date_alter_sell_date'),
        ('apps_stocks', '0003_alter_dividend_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyDividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(default=0)),
                ('custody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_dividends', to='apps_operations.custody')),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_stocks.dividend')),
            ],
        ),
    ]
