# Generated by Django 5.1.4 on 2025-01-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_operations', '0006_rename_custodydividends_custodydividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custody',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='custody',
            name='volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
